volumes:
  static_volume:
  postgres_data:
services:
  backend:
    build: ./backend
    command: /bin/bash -c "source entrypoint.sh"
    volumes:
      - ./backend:/backend/
      - static_volume:/backend/pdf_chat/staticfiles
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - ./backend/pdf_chat/.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - backend
    volumes:
      - static_volume:/backend/pdf_chat/staticfiles
