# Generated by Django 5.0.2 on 2024-03-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_chatmessage_downvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title_slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
