# Generated by Django 5.0.2 on 2024-03-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_room_title_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='room',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='room',
            name='views',
        ),
    ]
