# Generated by Django 5.0.1 on 2024-01-12 14:50

import chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('biology', 'biology'), ('chemistry', 'chemistry'), ('physics', 'physics'), ('math', 'math'), ('english', 'english'), ('agriculture', 'agriculture')], max_length=150)),
                ('grade', models.CharField(choices=[('9', 'grade nine'), ('10', 'grade ten'), ('11', 'grade eleven'), ('12', 'grade twelve')], max_length=2)),
                ('pdf', models.FileField(upload_to=chat.models.pdfUploadPath)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('biology', 'biology'), ('chemistry', 'chemistry'), ('physics', 'physics'), ('math', 'math'), ('english', 'english'), ('agriculture', 'agriculture')], max_length=150)),
                ('grade', models.CharField(choices=[('9', 'grade nine'), ('10', 'grade ten'), ('11', 'grade eleven'), ('12', 'grade twelve')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ai', 'ai'), ('user', 'user')], max_length=15)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
            ],
        ),
    ]
