# Generated by Django 5.0.2 on 2024-02-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['date']},
        ),
        migrations.AlterUniqueTogether(
            name='pdf',
            unique_together={('subject', 'grade')},
        ),
    ]
