# Generated by Django 5.0.2 on 2024-03-11 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='type',
            field=models.CharField(choices=[('Ai', 'Ai'), ('Human', 'Human')], default='Human', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('user', 'subject', 'grade')},
        ),
    ]
